### ISSUE TITLE
Issue with having too many prefences.

### ISSUE THREAD

**Issue by LeCloutPanda** [nwfistere/VSMenuModHelper#1]
I noticed if I use the ExampleMod and make my own preferences that it overflows off the menu and doesn't scroll.
 
I've attached an image below to show an example (Don't mind the icon as it was a temp one)
![image](https://github.com/nwfistere/VSMenuModHelper/assets/53411604/cc622aa8-c443-4b04-95e5-017116ae6959)

**Comment by nwfistere** [comment]
Thanks for submitting an issue!

I’m open for suggestions on a fix, right now my two ideas are:
 1. A scroll bar to handle overflowing tabs
 Or
 2. Adding a second column and extending the width of the tab section
 
 
I like the idea of #2 more, but depending on the background it might be more work.

**Comment by LeCloutPanda** [comment]
The second option would take more time and effort, but it would make modded choices look different from regular ones. However, we'd need to add a scrolling feature as more mods come in.

I also noticed that when we try to load the resource that's not there, it just shows an error and creates a blank icon. Maybe we could link to a file hosted on GitHub/Discord instead? Like putting the stuff on GitHub. But I'm not completely sure about that.

Edit
In addition to hosting the logo on GitHub/Discord maybe having a option to make the icon use different filtering modes like Nearest neighbour etc would be nice.

**Comment by nwfistere** [comment]
Thanks for the input, I created #2 for allowing urls and #4 for allowing mods to supply their own images or textures.

**Comment by CallMeEchoCodes** [comment]
yeah im getting this too. i would say a scrollbar would be the best thing to do.

**Comment by nwfistere** [comment]
I took a look at this a few days ago, it looks like if I duplicate the tab container it automatically displays to the right of the tab page. I'm going to start working on a fix for this (whether it's a scrollbar or something else)

**Comment by CallMeEchoCodes** [comment]
i think the scrollbar is better for the future. if a ton of mods get made then the bars will still run off screen

**Comment by LeCloutPanda** [comment]
A mixture of both will definitely help, clearly having two lists one for vanilla and one for mods will make it more distinguishable and if the Devs decided to add more tabs neither the modded or vanilla will interfere with each other

**Comment by CallMeEchoCodes** [comment]
maybe have 2 lists and the modded one has a scroll bar?

**Comment by nwfistere** [comment]
@LeCloutPanda @CallMeEchoCodes Check the video in the pull request I just opened. 

I have scrolling working on the original tab bar. It was a lot harder than I thought it would be.

I didn't add an actual scroll bar on it, so users would have to either scroll with their wheel or drag the tabs with their mouse.

Let me know what you think.

**Comment by LeCloutPanda** [comment]
That looks like it'll work beautifully, if the idea of having seperate list is still a possible that would be nice but simply adding that makes it so much easier. Well done.

**Comment by CallMeEchoCodes** [comment]
that looks great! only thing i think it needs is for the scrollbar to be visible but thats minor
